# production:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  hourly_hackatime_refresh:
    class: HourlyHackatimeRefreshJob
    queue: default
    schedule: every hour
    description: "Refresh Hackatime stats for all users with Hackatime enabled"

  generate_stonk_reports:
    class: GenerateStonkReportJob
    schedule: every day
